from md.category import *

CATEGORY_MAPPER = { 
  "ELSS" : elss,
  "Small Cap" : small_cap,
  "Mid Cap" : mid_cap,
  "Sectoral / Thematic" : sectoral_thematic,
  "Index" : index,
  "Large Cap" : large_cap,
  "Contra" : contra,
  "Dynamic Asset Allocation" : dynamic_asset_allocation,
  "Aggressive Hybrid" : aggressive_hybrid,
  "Multi Cap" : multi_cap,
  "Large & MidCap" : large_midcap,
  "FoF Overseas/Domestic" : fof_overseas_domestic,
  "Flexi Cap" : flexi_cap,
  "Multi Asset Allocation" : multi_asset_allocation,
  "Liquid" : liquid,
  "Value" : value,
  "Retirement" : retirement,
  "Overnight" : overnight,
  "Dividend Yield" : dividend_yield,
  "Focused" : focused,
  "Conservative Hybrid" : conservative_hybrid,
  "Short Duration" : short_duration,
  "Medium Duration" : medium_duration,
  "Banking and PSU" : banking_and_psu,
  "Arbitrage" : arbitrage,
  "Ultra Short Duration" : ultra_short_duration,
  "Gilt" : gilt,
  "Equity Savings" : equity_savings,
  "Corporate Bond" : corporate_bond,
  "Long Duration" : long_duration,
  "Dynamic Bond" : dynamic_bond,
  "Money Market" : money_market,
  "Credit Risk" : credit_risk,
  "Children's" : children,
  "Gilt 10 year" : gilt_10_year,
  "FMP" : fmp,
  "Low Duration" : low_duration,
  "Balanced Hybrid" : balanced_hybrid,
  "Medium to Long Duration" : medium_to_long_duration,
  "Floater" : floater
} 